# Generated by Django 5.1.5 on 2025-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back-end", "Back-end"),
                    ("front-end", "Front-end"),
                    ("iOS", "iOS"),
                    ("android", "Android"),
                ],
                default="back-end",
                max_length=10,
            ),
        ),
    ]
