# Generated by Django 5.1.5 on 2025-02-03 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_issue_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
